---
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
    - action: replace
      regex: container_networks_(.+)
      replacement: network:container_network_$1
      sourceLabels:
      - __name__
      targetLabel: __name__
